version: '3.9'

volumes:
  go_exercise:
    name: go_exercise

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - go_exercise:/var/lib/postgresql/data
