version: '3.9'

volumes:
  simple_transaction:
    name: simple_transaction

services:
  postgres:
    image: postgres:14-alpine
    restart: always
    ports:
      - "5758:5432"
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - simple_transaction:/var/lib/postgresql/data
