apiVersion: apps/v1
kind: Deployment
metadata:
  name: squirtle-api-deployment
  labels:
    app: squirtle-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squirtle-api
  template:
    metadata:
      labels:
        app: squirtle-api
    spec:
      containers:
        - name: squirtle-api
          image: 510611342067.dkr.ecr.ap-southeast-1.amazonaws.com/squirtle:46f4b05e7f289e70bbdf8cedfdfadfe14ebf3a2a
          ports:
            - containerPort: 8080
