apiVersion: v1
kind: Service
metadata:
  name: squirtle-api-service
spec:
  selector:
    app.kubernetes.io/name: squirtle-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
