name: Build and Push Docker Image

on:
  push:
    branches: ["master"]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Create env file
        run: |
          touch staging.env
          echo APP_ENVIRONMENT=${{ secrets.APP_ENVIRONMENT }} >> staging.env
          echo HTTP_SERVER_ADDRESS=${{ secrets.HTTP_SERVER_ADDRESS }} >> staging.env
          echo GRPC_SERVER_ADDRESS=${{ secrets.GRPC_SERVER_ADDRESS }} >> staging.env
          echo DB_DRIVER=${{ secrets.DB_DRIVER  }} >> staging.env
          echo DB_SOURCE=${{ secrets.DB_SOURCE }} >> staging.env
          echo MIGRATION_SOURCE_URL=${{ secrets.MIGRATION_SOURCE_URL}} >> staging.env
          echo TOKEN_SYMMETRIC_KEY=${{ secrets.TOKEN_SYMMETRIC_KEY }} >> staging.env
          echo ACCESS_TOKEN_DURATION=${{ secrets.ACCESS_TOKEN_DURATION }} >> staging.env
          echo REFRESH_TOKEN_DURATION=${{ secrets.REFRESH_TOKEN_DURATION }} >> staging.env
          cat staging.env

      - name: Build and push docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ardhon/simple-transaction:latest
