name: Deploy

on:
  push:
    branches: ["master"]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.15

      - name: Create env file
        run: |
          touch app.env
          echo SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS}} >> app.env
          echo DB_DRIVER=${{ secrets.DB_DRIVER  }} >> app.env
          echo DB_SOURCE=${{ secrets.DB_SOURCE}} >> app.env
          echo TOKEN_SYMMETRIC_KEY=${{ secrets.TOKEN_SYMMETRIC_KEY  }} >> app.env
          echo ACCESS_TOKEN_DURATION=${{ secrets.ACCESS_TOKEN_DURATION  }} >> app.env
          cat app.env

      - name: Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
